# Generated by Django 4.2.8 on 2024-01-03 08:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='用户名', max_length=30, unique=True)),
                ('password', models.CharField(help_text='用户密码', max_length=30)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', help_text='角色名', max_length=10)),
                ('phone', models.CharField(help_text='电话号码', max_length=20, null=True)),
                ('email', models.CharField(help_text='邮箱账号', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
