# Generated by Django 2.1.4 on 2019-02-22 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='考试名称')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='结束时间')),
                ('student_num', models.IntegerField(default=0, verbose_name='应参加人数')),
                ('actual_num', models.IntegerField(default=0, verbose_name='实际参加人数')),
                ('exam_state', models.CharField(choices=[('0', '考试未开始'), ('1', '考试进行中'), ('2', '考试已结束')], default='0', max_length=1, verbose_name='考试状态')),
                ('exam_type', models.CharField(choices=[('pt', '普通'), ('ts', '特殊')], default='pt', max_length=2, verbose_name='类型')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考试信息',
                'verbose_name_plural': '考试信息',
            },
        ),
        migrations.CreateModel(
            name='ExamPaperInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '考试试卷信息',
                'verbose_name_plural': '考试试卷信息',
            },
        ),
        migrations.CreateModel(
            name='ExamStudentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.ExaminationInfo', verbose_name='考试信息')),
            ],
            options={
                'verbose_name': '考试考生信息',
                'verbose_name_plural': '考试考生信息',
            },
        ),
    ]
