# Generated by Django 2.1.4 on 2019-02-22 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190222_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=20, verbose_name='学生姓名')),
                ('student_id', models.CharField(default='', max_length=20, verbose_name='学号')),
                ('student_class', models.CharField(default='', max_length=10, verbose_name='学生班级')),
                ('student_school', models.CharField(default='', max_length=100, verbose_name='学生所在学校')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
    ]
