# Generated by Django 2.1.4 on 2019-02-22 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_studentsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=20, verbose_name='科目')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('teacher_school', models.CharField(default='', max_length=100, verbose_name='老师所在学校')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '老师信息',
                'verbose_name_plural': '老师信息',
            },
        ),
    ]
