# Generated by Django 2.1.4 on 2019-02-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_teacherinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='teacher_name',
            field=models.CharField(default='', max_length=20, verbose_name='老师姓名'),
        ),
    ]
