# Generated by Django 2.1.4 on 2019-02-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_teacherinfo_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinfo',
            name='subject',
        ),
    ]
