# Generated by Django 4.2.8 on 2024-02-23 06:06

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_id', models.CharField(help_text='考试ID', max_length=255)),
                ('student_id', models.CharField(help_text='学生ID', max_length=255)),
                ('result_mark', models.PositiveIntegerField(default=0, help_text='学生考试得分')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='学生开始考试的时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='学生结束考试的时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'exam_result',
            },
        ),
    ]
