# Generated by Django 4.2.8 on 2024-02-23 06:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResult', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_result_id', models.CharField(help_text='考试结果ID', max_length=255)),
                ('question_id', models.CharField(help_text='试题ID', max_length=255)),
                ('mark', models.PositiveIntegerField(default=0, help_text='试题得分')),
                ('solution', models.TextField(help_text='学生作答结果', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
            ],
            options={
                'db_table': 'exam_result_detail',
            },
        ),
    ]
