# Generated by Django 4.2.8 on 2024-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResult', '0002_examresultdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresultdetail',
            name='solution',
            field=models.TextField(default=None, help_text='学生作答结果', max_length=500),
        ),
    ]
