# Generated by Django 4.2.8 on 2024-10-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResult', '0004_alter_examresult_id_alter_examresultdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresultdetail',
            name='solution',
            field=models.TextField(blank=True, help_text='学生作答结果', max_length=500, null=True),
        ),
    ]
