# Generated by Django 4.2.8 on 2024-10-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResult', '0005_alter_examresultdetail_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresultdetail',
            name='mark',
            field=models.FloatField(default=0, help_text='试题得分'),
        ),
    ]
