# Generated by Django 4.2.8 on 2024-02-06 02:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='试卷标题', max_length=100)),
                ('description', models.TextField(blank=True, help_text='试卷描述', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='答题建议时长')),
                ('total_marks', models.PositiveIntegerField(default=100, help_text='总分数')),
                ('is_published', models.BooleanField(default=False, help_text='是否发布')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_user', models.CharField(help_text='创建人', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('updated_user', models.CharField(help_text='更新人', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'paper',
            },
        ),
    ]
