# Generated by Django 4.2.8 on 2024-02-06 02:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PaperManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(help_text='试卷ID', max_length=50)),
                ('question_id', models.CharField(help_text='试题ID', max_length=50)),
                ('sequence_number', models.PositiveIntegerField(default=1, help_text='试题顺序')),
                ('marks', models.PositiveIntegerField(default=5, help_text='分数')),
                ('module', models.CharField(help_text='所属模块', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
            ],
            options={
                'db_table': 'paper_questions',
            },
        ),
    ]
