# Generated by Django 4.2.8 on 2024-02-06 03:03

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PaperManagement', '0002_paperquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(help_text='试卷ID', max_length=50)),
                ('title', models.CharField(help_text='模块名称', max_length=100)),
                ('description', models.TextField(blank=True, help_text='模块描述', null=True)),
                ('sequence_number', models.PositiveIntegerField(default=1, help_text='模块顺序')),
                ('created_user', models.CharField(help_text='创建人', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('updated_user', models.CharField(help_text='更新人', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'paper_module',
            },
        ),
    ]
