# Generated by Django 4.2.8 on 2024-03-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperManagement', '0005_paper_is_deleted_alter_paperquestions_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_public',
            field=models.BooleanField(default=False, help_text='是否属于公共试卷库'),
        ),
    ]
