# Generated by Django 4.2.8 on 2024-10-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaperManagement', '0007_alter_paperquestions_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papermodule',
            name='paper_id',
            field=models.CharField(help_text='试卷ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='paperquestions',
            name='paper_id',
            field=models.CharField(help_text='试卷ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='paperquestions',
            name='question_id',
            field=models.CharField(help_text='试题ID', max_length=255),
        ),
    ]
