# Generated by Django 2.1.4 on 2019-02-22 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=100, verbose_name='选项')),
                ('is_right', models.BooleanField(default=True, verbose_name='是否为正确答案')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '试题选项信息',
                'verbose_name_plural': '试题选项信息',
            },
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(default='', max_length=20, verbose_name='科目名称')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科目信息',
                'verbose_name_plural': '科目信息',
            },
        ),
        migrations.CreateModel(
            name='TestQuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='试题题目')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
                ('tq_type', models.CharField(choices=[('xz', '选择'), ('pd', '判断'), ('tk', '填空')], default='xz', max_length=2, verbose_name='试题类型')),
                ('tq_degree', models.CharField(choices=[('jd', '简单'), ('zd', '中等'), ('kn', '困难')], default='jd', max_length=2, verbose_name='试题难度')),
                ('image', models.ImageField(max_length=200, upload_to='test_question/%Y/%m', verbose_name='试题图片')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_share', models.BooleanField(default=False, verbose_name='是否分享')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('creat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testquestion.SubjectInfo', verbose_name='所属科目')),
            ],
            options={
                'verbose_name': '试题信息',
                'verbose_name_plural': '试题信息',
            },
        ),
        migrations.AddField(
            model_name='optioninfo',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testquestion.TestQuestionInfo', verbose_name='试题信息'),
        ),
    ]
