# Generated by Django 2.1.4 on 2019-02-22 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='', max_length=100, verbose_name='选项')),
                ('is_right', models.BooleanField(default=True, verbose_name='是否为正确答案')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '试题选项信息',
                'verbose_name_plural': '试题选项信息',
            },
        ),
        migrations.CreateModel(
            name='TestQuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='试题题目')),
                ('score', models.IntegerField(default=0, verbose_name='分值')),
                ('tq_type', models.CharField(choices=[('xz', '选择'), ('pd', '判断'), ('tk', '填空')], default='xz', max_length=2, verbose_name='试题类型')),
                ('tq_degree', models.CharField(choices=[('jd', '简单'), ('zd', '中等'), ('kn', '困难')], default='jd', max_length=2, verbose_name='试题难度')),
                ('image', models.ImageField(max_length=200, upload_to='test_question/%Y/%m', verbose_name='试题图片')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_share', models.BooleanField(default=False, verbose_name='是否分享')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '试题信息',
                'verbose_name_plural': '试题信息',
            },
        ),
    ]
