# Generated by Django 4.2.8 on 2024-01-16 11:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.TextField(help_text='试题标题', max_length=500)),
                ('answer', models.TextField(help_text='试题答案', max_length=500)),
                ('type', models.CharField(choices=[('select', 'Select'), ('judge', 'Judge')], default='select', help_text='试题类型', max_length=10)),
                ('status', models.BooleanField(default=True, help_text='试题状态')),
                ('created_user', models.CharField(help_text='创建人', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('updated_user', models.CharField(help_text='更新人', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
