# Generated by Django 4.2.8 on 2024-01-22 11:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionManagement', '0003_questions_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(help_text='试题ID', max_length=50)),
                ('collector', models.CharField(help_text='收藏者ID', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
            ],
            options={
                'db_table': 'questions_favorite',
            },
        ),
    ]
