# Generated by Django 4.2.8 on 2024-01-30 11:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionManagement', '0004_questionsfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(help_text='试题ID', max_length=50)),
                ('explanation', models.TextField(help_text='错题解析', max_length=500)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='select', help_text='错题难度', max_length=10)),
                ('collector', models.CharField(help_text='收藏者ID', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
            ],
            options={
                'db_table': 'error_archive',
            },
        ),
    ]
