# Generated by Django 4.2.8 on 2024-10-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionManagement', '0008_alter_questions_trial_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorarchive',
            name='collector',
            field=models.CharField(help_text='收藏者ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='errorarchive',
            name='question_id',
            field=models.CharField(help_text='试题ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='questionsfavorite',
            name='collector',
            field=models.CharField(help_text='收藏者ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='questionsfavorite',
            name='question_id',
            field=models.CharField(help_text='试题ID', max_length=255),
        ),
    ]
