# Generated by Django 4.2.8 on 2024-02-21 06:04

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper_id', models.CharField(help_text='绑定试卷ID', max_length=255)),
                ('title', models.CharField(help_text='试卷标题', max_length=100)),
                ('description', models.TextField(blank=True, help_text='试卷描述', null=True)),
                ('start_time', models.DateTimeField(verbose_name='考试开始时间')),
                ('end_time', models.DateTimeField(verbose_name='考试结束时间')),
                ('pass_mark', models.PositiveIntegerField(default=60, help_text='及格分数')),
                ('is_published', models.BooleanField(default=False, help_text='是否发布')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('created_user', models.CharField(help_text='创建人', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('updated_user', models.CharField(help_text='更新人', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'exam',
            },
        ),
    ]
