# Generated by Django 2.1.4 on 2019-02-22 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('testquestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testpaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscores',
            name='user',
            field=models.ForeignKey(on_delete=models.Model, to='user.StudentsInfo', verbose_name='学生信息'),
        ),
        migrations.AddField(
            model_name='testpapertestq',
            name='test_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpaper.TestPaperInfo', verbose_name='试卷'),
        ),
        migrations.AddField(
            model_name='testpapertestq',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testquestion.TestQuestionInfo', verbose_name='试题'),
        ),
        migrations.AddField(
            model_name='testpaperinfo',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='testpaperinfo',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.SubjectInfo', verbose_name='试卷所属科目'),
        ),
    ]
